template = "pico8"
code = "main.lua"
[[sprite_sheet]] # 0
path = "tilemap_packed.tsx"
[[sprite_sheet]] # 1
path = "custom2.png"
sprite_size = [16, 16]
sprite_counts = [3, 1]
[[map]] # 0
ldtk = "outside.tmx"
[[map]] # 1
ldtk = "inside.tmx"
[[map]] # 2
ldtk = "Lillys house inside.tmx"
[[map]] # 3
ldtk = "Lillys house outside.tmx"
[[map]] # 4
ldtk = "black smith inside town.tmx"
# [[map]] # 5
# ldtk = "table2.tmx"
