template = "pico8"
code = "main.lua"
[[sprite_sheet]]
path = "tilemap_packed.tsx"
# path = "tilemap_packed.png"
# sprite_size = [16, 16]
# sprite_counts = [12, 11]
[[map]] # 0
ldtk = "outside.tmx"
[[map]] # 1
ldtk = "inside.tmx"
[[map]] # 2
ldtk = "Lillys house inside.tmx"
[[map]] # 3
ldtk = "Lillys house outside.tmx"
[[map]] # 4
ldtk = "black smith inside town.tmx"
